### ISSUE TITLE
     "message": "Invalid Phone Number"

### ISSUE THREAD

**Issue by sreebash** [Chetan45s/Django-Rest-API-OTP-authentication#1]
When I hit http://127.0.0.1:8000/send_otp endpoint then raised the following error:

HTTP 400 Bad Request
Allow: POST, OPTIONS
Content-Type: application/json
Vary: Accept

{
    "message": "Invalid Phone Number"
}
How to fix the problem please?

**Comment by Chetan45s** [comment]
Phone Number Should be of 10 digit.

Refer : Line 29,  https://github.com/Chetan45s/Django-Rest-API-OTP-authentication/blob/main/All_Users/views.py
